services:
  app:
    image: super-server-backend

    build:
      context: .
      dockerfile: Docker/Dockerfile

    ports:
      - "8000:8000"
      
    volumes:
      - /home/artem/super/resources:/app/resources